version: "3.8"
services:
  mysqldb1:
    image: mysql
    container_name: db-devices
    restart: on-failure
    ports:
      - "3310:3306"
    environment:
      MYSQL_DATABASE: device-management
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    networks:
      - db-users-network
  device-management-app:
    hostname: backend
    restart: on-failure
    depends_on:
      - mysqldb1
    links:
      - mysqldb1
    image: device-management-app
    container_name: device-management-container
    build: .
    ports:
      - "8083:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local-docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb1:3306/device-management
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
    networks:
      - db-users-network

networks:
  db-users-network:
    external: true