version: "3.8"
services:
  mysqldbuser:
    image: mysql
    container_name: db-users
    restart: on-failure
    ports:
      - "3311:3306"
    environment:
      MYSQL_DATABASE: user-management
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    networks:
      - db-users-network
  user-management-app:
    hostname: backend
    restart: on-failure
    depends_on:
      - mysqldbuser
    links:
      - mysqldbuser
    image: user-management-app
    container_name: user-management-container
    build: .
    ports:
      - "8084:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local-docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldbuser:3306/user-management
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
    networks:
      - db-users-network

networks:
  db-users-network:
    external: true